### ISSUE TITLE
charmap

### ISSUE THREAD

**Issue by H3ckforfun** [HideakiAtsuyo/Kramered#7]
Error:
Traceback (most recent call last):
  File "C:\Users\fohrt\AppData\Local\Temp\123.py", line 15, in <module>
    print(deobfuscated)
  File "C:\Users\fohrt\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-10: character maps to <undefined>

**Comment by HideakiAtsuyo** [comment]
> Error: Traceback (most recent call last): File "C:\Users\fohrt\AppData\Local\Temp\123.py", line 15, in print(deobfuscated) File "C:\Users\fohrt\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-10: character maps to

I will check this out later, can you send the script you tried to deobfuscate ?

**Comment by HideakiAtsuyo** [comment]
Was it [DeadWare-Webhook-Spammer#PR1](https://github.com/H3ckforfun/DeadWare-Webhook-Spammer/pull/1) or [H3ckforfun#PR1](https://github.com/H3ckforfun/ceres-raid-tool/pull/1) or another script ?

**Comment by H3ckforfun** [comment]
> Was it [DeadWare-Webhook-Spammer#PR1](https://github.com/H3ckforfun/DeadWare-Webhook-Spammer/pull/1) or [H3ckforfun#PR1](https://github.com/H3ckforfun/ceres-raid-tool/pull/1) or another script ?

both and can u send me the webhook lamo

**Comment by HideakiAtsuyo** [comment]
> > Was it [DeadWare-Webhook-Spammer#PR1](https://github.com/H3ckforfun/DeadWare-Webhook-Spammer/pull/1) or [H3ckforfun#PR1](https://github.com/H3ckforfun/ceres-raid-tool/pull/1) or another script ?
> 
> both and can u send me the webhook lamo

 Check both PRs they contain clean code with webhooks :)

**Comment by H3ckforfun** [comment]
nah man i mean the updated version XD

**Comment by HideakiAtsuyo** [comment]
> nah man i mean the updated version XD

You said wdbhook 😳

**Comment by H3ckforfun** [comment]
> 

so u cant get it?

**Comment by HideakiAtsuyo** [comment]
> > 
> 
> so u cant get it?

I can ?

[DeadWare-Webhook-Spammer#PR1#L8](https://github.com/H3ckforfun/DeadWare-Webhook-Spammer/blob/41faf80248aae1073bcdffa36130e5dd9a2a5aad/DeadWare-Webhook-Violator.py#L8) & [ceres-raid-tool#PR1#L13](https://github.com/H3ckforfun/ceres-raid-tool/blob/9b78520c9c811ae9eba41e8e85c4011b016e5f6b/ceres-raid-tool/Ceres-nuker-V2.3.py#L13)

**Comment by HideakiAtsuyo** [comment]
I deleted both

**Comment by H3ckforfun** [comment]
>

> I deleted both

i mean the latest one

**Comment by HideakiAtsuyo** [comment]
> > 
> 
> > I deleted both
> 
> i mean the latest one

Send link

**Comment by H3ckforfun** [comment]
> > > 
> > 
> > 
> > > I deleted both
> > 
> > 
> > i mean the latest one
> 
> Send link

https://github.com/H3ckforfun/ceres-raid-tool/releases/tag/raid

**Comment by HideakiAtsuyo** [comment]
> > > > 
> > > 
> > > 
> > > > I deleted both
> > > 
> > > 
> > > i mean the latest one
> > 
> > 
> > Send link
> 
> https://github.com/H3ckforfun/ceres-raid-tool/releases/tag/raid

Is it the same as the file in the repo ? If yes the webhook is deleted

**Comment by H3ckforfun** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > I deleted both
> > > > 
> > > > 
> > > > i mean the latest one
> > > 
> > > 
> > > Send link
> > 
> > 
> > https://github.com/H3ckforfun/ceres-raid-tool/releases/tag/raid
> 
> Is it the same as the file in the repo ? If yes the webhook is deleted

its not i updated the file yesterday

**Comment by HideakiAtsuyo** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > > I deleted both
> > > > > 
> > > > > 
> > > > > i mean the latest one
> > > > 
> > > > 
> > > > Send link
> > > 
> > > 
> > > https://github.com/H3ckforfun/ceres-raid-tool/releases/tag/raid
> > 
> > 
> > Is it the same as the file in the repo ? If yes the webhook is deleted
> 
> its not i updated the file yesterday

Ok I will do it later

**Comment by H3ckforfun** [comment]
> 

alr

**Comment by HideakiAtsuyo** [comment]
You just stacked it multiple times.
I will not waste any time on it.
